<html>
<head>
<meta http-equiv="Content-Type" content="text/html; utf-8">
    <title>Emaxx Website Manager</title>
    <link rel="stylesheet" type="text/css" href="/ext/resources/css/ext-all.css" />
    <script type="text/javascript" src="/ext/adapter/ext/ext-base<?php if (APPLICATION_ENV != 'production') echo '-debug'; ?>.js"></script>
    <script type="text/javascript" src="/ext/ext-all<?php if (APPLICATION_ENV != 'production') echo '-debug'; ?>.js"></script>    
    <script type="text/javascript" src="/index/js/module/login"></script>    
</head>
<body>
</body>
</html>