<html>
<head>
<meta http-equiv="Content-Type" content="text/html; utf-8">
    <title>Emaxx Website Manager</title>
    <link rel="stylesheet" type="text/css" href="/ext/resources/css/ext-all.css" />
    <link rel="stylesheet" type="text/css" href="/ext/examples/ux/css/ux-all.css" />
    <script type="text/javascript" src="/ext/adapter/ext/ext-base<?php if (APPLICATION_ENV != 'production') echo '-debug'; ?>.js"></script>
    <script type="text/javascript" src="/ext/ext-all<?php if (APPLICATION_ENV != 'production') echo '-debug'; ?>.js"></script>    
    <script type="text/javascript" src="/ext/examples/ux/ux-all<?php if (APPLICATION_ENV != 'production') echo '-debug'; ?>.js"></script>    
    <script type="text/javascript" src="/index/js/module/main"></script>
    <link rel="stylesheet" href="/css/icons.css" type="text/css" media="screen" title="no title" charset="utf-8" />
    <style type="text/css" media="screen">
        div.address {
            padding: 10px;
            font-family: arial,tahoma,helvetica,sans-serif;
            font-size: 11px;
            border: solid 1px white;
        }
        
        .icn-dispatch {
            background-image: url(/img/dispatch.png) !important;
        }
        
        .icn-complete {
            background-image: url(/img/complete.png) !important;
        }
        
        .icn-accept {
            background-image: url(/img/accept.png) !important;
        }
        
        .icn-reject {
            background-image: url(/img/reject.png) !important;
        }
        
        .icn-print {
            background-image: url(/img/print.png) !important;
        }
        
        .order-warning {
            border: 1px solid yellow;
        }
        .order-late {
            border: 1px solid red;
        }
        
    </style>
</head>
<body>
</body>
</html>